const projects = [
  {
    title: "Lightweight Feedback System",
    short: "A React + Flask based feedback tool with sentiment analysis and PDF export, allowing managers and employees to exchange feedback, analyze sentiment, and export reports.",
    liveLink: "https://lightweight-feedback-system-1.netlify.app/",
    category: "Web App",
    technologies: ["React", "Flask", "Python", "PDF Export", "Sentiment Analysis"],
    highlights: ["Feedback Management", "Sentiment Analysis", "PDF Reports"],
  },
  {
    title: "Candy Crush Game",
    short: "Classic Candy Crush game using drag-and-drop and real-time state updates.",
    liveLink: "https://candy-crush-inspired-game.onrender.com/",
    category: "Game",
    technologies: ["JavaScript", "HTML", "CSS", "Drag-and-Drop"],
    highlights: ["Interactive Gameplay", "Responsive Design", "Real-Time Updates"],
  },
  {
    title: "Fitness Booking API",
    short: "FastAPI-based REST API for managing fitness class bookings with robust endpoints and data validation.",
    liveLink: "https://fitness-booking-api.onrender.com/docs",
    category: "API",
    technologies: ["FastAPI", "Python", "REST API", "SQLAlchemy"],
    highlights: ["Booking Management", "API Documentation", "Secure Endpoints"],
  },
  {
    title: "Online Quiz Platform",
    short: "Quiz app with timer, leaderboard, multiple question types, and scoring system.",
    liveLink: "https://vats-quiz-app.netlify.app/",
    category: "Web App",
    technologies: ["React", "JavaScript", "CSS", "Timer", "Leaderboard"],
    highlights: ["Timer-Based Quizzes", "Leaderboard", "Multiple Question Types"],
  },
  {
    title: "Tic Tac Toe Game",
    short: "Classic Tic Tac Toe game with responsive UI and win detection.",
    liveLink: "https://vats-game1.netlify.app/",
    category: "Game",
    technologies: ["JavaScript", "HTML", "CSS", "Game Logic"],
    highlights: ["Win Detection", "Responsive UI", "Interactive Gameplay"],
  },
  {
    title: "Hubspot OAuth Integration",
    short: "Backend integration using Python + FastAPI to implement HubSpot OAuth authentication and automated item loading logic.",
    liveLink: "https://github.com/abhishekvats29/Hubspot-Integration",
    category: "Backend/API",
    technologies: ["Python", "FastAPI", "OAuth", "HubSpot API"],
    highlights: ["OAuth Authentication", "Automated Item Loading", "Backend Integration"],
  },
  {
    title: "Vehicle Registration Investor Dashboard",
    short: "Interactive dashboard visualizing Year-over-Year (YoY) and Quarter-over-Quarter (QoQ) growth in vehicle registrations for investor insights.",
    liveLink: "https://vehicle-registrations-investor-dashboard-in.streamlit.app/",
    category: "Dashboard",
    technologies: ["React", "Chart.js", "JavaScript", "Data Visualization"],
    highlights: ["YoY & QoQ Analysis", "Interactive Charts", "Investor Insights"],
  },
  {
    title: "OneBox Email Aggregator",
    short: "Connects multiple email accounts into a single inbox. Features real-time email syncing and an AI chatbot suggesting smart replies based on content.",
    liveLink: "https://onebox-email-aggregator-z6h0.onrender.com/",
    category: "Web App / AI",
    technologies: ["React", "Node.js", "AI Chatbot", "Real-Time Sync"],
    highlights: ["Multi-Email Aggregation", "AI Smart Replies", "Real-Time Updates"],
  },
  {
    title: "Currency Converter App",
    short: "💱 Convert between multiple currencies instantly with real-time exchange rates, enter custom amounts, and see dynamic conversions update automatically for accurate currency calculations.",
    liveLink: "https://currency-converter-app-in.netlify.app/",
    category: "App",
    technologies: ["React", "JavaScript", "API", "Real-Time Sync"],
    highlights: ["Currency convert", "Exchange world wide currency", "Real-Time Updates"],
  },
];

export default projects;
